# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20180623_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotel_image'),
        ),
    ]
